name: mostawak
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ✅ UI & Utils
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  pinput: ^5.0.2
  intl: ^0.20.2
  flutter_svg: ^2.2.1
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.3.4

  # ✅ Firebase & Google (متوافقة سوا)
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/Bebas_Neue/BebasNeue-Regular.ttf

    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf

    - family: BigShoulders
      fonts:
        - asset: assets/fonts/Big_Shoulders/static/BigShoulders_60pt-Bold.ttf
        - asset: assets/fonts/Big_Shoulders/static/BigShoulders_18pt-ExtraBold.ttf

flutter_intl:
  enabled: true
