// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQAaaidV0RD5vB29TnaNtXH7iVQEjdp2c',
    appId: '1:523845928813:web:6e5c0213a59675dc37bc64',
    messagingSenderId: '523845928813',
    projectId: 'mostawak-22fc3',
    authDomain: 'mostawak-22fc3.firebaseapp.com',
    storageBucket: 'mostawak-22fc3.firebasestorage.app',
    measurementId: 'G-VZ6THW628N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfkSvCJhjsH9B8geoDyEbDu7n1OkOapU4',
    appId: '1:523845928813:android:22e4ff69d0e8149d37bc64',
    messagingSenderId: '523845928813',
    projectId: 'mostawak-22fc3',
    storageBucket: 'mostawak-22fc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeTwobPtMY7hdYcHshH71MGyoD08HGEEg',
    appId: '1:523845928813:ios:4241ca29b2aba81737bc64',
    messagingSenderId: '523845928813',
    projectId: 'mostawak-22fc3',
    storageBucket: 'mostawak-22fc3.firebasestorage.app',
    iosBundleId: 'com.example.mostawak',
  );
}
